"""initial control store

Revision ID: 8d9b520c8045
Revises: 
Create Date: 2026-09-22 16:32:28.139216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('workspace_graph_name', sa.String(), nullable=False),
    sa.Column('enablement_state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('investigation_history',
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conversation_json', sa.JSON(), nullable=False),
    sa.Column('known_entities_json', sa.JSON(), nullable=False),
    sa.Column('tool_call_trace_json', sa.JSON(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('investigation_id')
    )
    op.create_index(op.f('ix_investigation_history_tenant_id'), 'investigation_history', ['tenant_id'], unique=False)
    op.create_table('policy_config',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('approval_thresholds', sa.JSON(), nullable=False),
    sa.Column('high_impact_conditions', sa.JSON(), nullable=False),
    sa.Column('cross_tenant_sharing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index(op.f('ix_policy_config_tenant_id'), 'policy_config', ['tenant_id'], unique=False)
    op.create_table('schema_mapping_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mapping_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_mapping_versions_tenant_id'), 'schema_mapping_versions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_mapping_versions_tenant_id'), table_name='schema_mapping_versions')
    op.drop_table('schema_mapping_versions')
    op.drop_index(op.f('ix_policy_config_tenant_id'), table_name='policy_config')
    op.drop_table('policy_config')
    op.drop_index(op.f('ix_investigation_history_tenant_id'), table_name='investigation_history')
    op.drop_table('investigation_history')
    op.drop_table('tenants')
    # ### end Alembic commands ###
